services:
  postgres:
    image: postgres:17
    container_name: postgres-db
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - microservices-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
  service-registry:
    image: service-registry:1.0.0
    container_name: service-registry
    ports:
      - "8761:8761"
    networks:
      - microservices-network
    depends_on:
      - postgres
  api-gateway:
    image: api-gateway:1.0.0
    container_name: api-gateway
    ports:
      - "8080:8080"
    networks:
      - microservices-network
    depends_on:
      - service-registry

  auth-service:
    image: auth-service:1.0.0
    container_name: auth-service
    ports:
      - "8081:8081"
    environment:
      - SPRING_DATASOURCE_USERNAME=${DB_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
      - SECURITY_JWT_SECRET=${JWT_SECRET}
      - SECURITY_JWT_EXPIRATION=${JWT_EXPIRATION}
    networks:
      - microservices-network
    depends_on:
      - service-registry
  course-service:
    image: course-service:1.0.0
    container_name: course-service
    ports:
      - "8082:8082"
    environment:
      - SPRING_DATASOURCE_USERNAME=${DB_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
    networks:
      - microservices-network
    depends_on:
      - service-registry
  user-interactions-service:
    image: user-interactions-service:1.0.0
    container_name: user-interactions-service
    ports:
      - "8083:8083"
    environment:
      - SPRING_DATASOURCE_USERNAME=${DB_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
    networks:
      - microservices-network
    depends_on:
      - service-registry
  yandex-cloud-service:
      image: yandex-cloud-service:1.0.0
      container_name: yandex-cloud-service
      ports:
        - "8084:8084"
      networks:
        - microservices-network
      environment:
        - S3_KEY = ${S3_KEY}
        - S3_SECRET = ${S3_SECRET}
        - S3_REGION = ${S3_REGION}
        - S3_ENDPOINT = ${S3_ENDPOINT}
        - S3_BUCKET = ${S3_BUCKET}
      depends_on:
        - service-registry
volumes:
  pg_data:

networks:
  microservices-network:
    driver: bridge